services:

  db-postgres:
    tty: true
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db
    volumes:
      - ./apps/frontend/src/libs/db/postgres/migrations:/docker-entrypoint-initdb.d

  db-redis:
    tty: true
    image: redis
    ports:
      - "6379:6379"

  db-mongodb:
    tty: true
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: db

  frontend:
    tty: true
    command: npm run dev -- --webpack
    build:
      context: ./apps
      dockerfile: frontend/Dockerfile.dev
    image: ba-tester/frontend
    environment:
      JWT_SECRET: "abc123"
      DATABASE_URL_POSTGRES: "postgresql://admin:12345678@db-postgres:5432/db?sslmode=disable"
      DATABASE_URL_REDIS: "redis://db-redis:6379"
      DATABASE_URL_MONGODB: "mongodb://admin:12345678@db-mongodb:27017/db?authSource=admin"
      SALT_ROUNDS: 1
      SUPER_ADMINS: '[{ "name": "Bastian", "email": "bastian.p@outlook.com", "password": "abc" }, { "name": "Bastian", "email": "bparedesp@falabella.com", "password": "abc" }]'
    ports:
      - "3000:3000"
    volumes:
      - /app/frontend/node_modules
      - ./apps/frontend:/app/frontend
      - ./apps/domain:/app/domain
    depends_on:
      - db-postgres
      - db-redis
      - db-mongodb

#  backend:
#    build:
#      context: ./apps
#      dockerfile: backend/Dockerfile.dev
#    image: trilba-tester/backend
#    environment:
#      JWT_SECRET: "abc123"
#      DATABASE_URL_POSTGRES: "postgresql://admin:12345678@db-postgres:5432/db?sslmode=disable"
#      DATABASE_URL_REDIS: "redis://db-redis:6379"
#      DATABASE_URL_MONGODB: "mongodb://admin:12345678@db-mongodb:27017/db?authSource=admin"
#      SALT_ROUNDS: 1
#      SUPER_ADMINS: '[{ "name": "Bastian", "email": "bastian.p@outlook.com", "password": "abc" }, { "name": "Bastian", "email": "bparedesp@falabella.com", "password": "abc" }]'
#    ports:
#      - "4000:4000"
#    depends_on:
#      - db-postgres
#      - db-redis
#      - db-mongodb
#    volumes:
#      - /app/backend/node_modules
#      - ./apps/backend:/app/backend
#      - ./apps/domain:/app/domain
