services:

  db-postgres:
    tty: true
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: db
    volumes:
      - ./src/libs/db/postgres/migrations:/docker-entrypoint-initdb.d

  db-redis:
    tty: true
    image: redis
    ports:
      - "6379:6379"

  db-mongodb:
    tty: true
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
      MONGO_INITDB_DATABASE: db

  app:
    tty: true
    command: sh -c "npm run postinstall && npm run dev"
    build:
      context: .
    image: ba-tester
    environment:
      JWT_SECRET: "abc123"
      DATABASE_URL_POSTGRES: "postgresql://admin:12345678@db-postgres:5432/db?sslmode=disable"
      DATABASE_URL_REDIS: "redis://db-redis:6379"
      DATABASE_URL_MONGODB: "mongodb+srv://Vercel-Admin-ba-tester:Hl6e7NKs5T880cUZ@ba-tester.6j1zvqx.mongodb.net/test?retryWrites=true&w=majority"
      SALT_ROUNDS: 10
      SUPER_ADMINS: '[{ "name": "Bastian", "email": "bastian.p@outlook.com", "password": "abc" }, { "name": "Bastian", "email": "bparedesp@falabella.com", "password": "abc" }]'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db-postgres
      - db-redis
      - db-mongodb
