services:

  db-postgres:
    tty: true
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    volumes:
      - ./src/libs/db/postgres/migrations:/docker-entrypoint-initdb.d

  db-redis:
    image: redis
    ports:
      - "6379:6379"

  db-mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo123
      MONGO_INITDB_DATABASE: appdb

  app:
    tty: true
    command: sh -c "npm run postinstall && npm run dev"
    build:
      context: .
    image: ba-tester
    environment:
      DATABASE_URL_POSTGRES: "postgresql://postgres:12345678@db-postgres:5432/postgres?sslmode=disable"
      DATABASE_URL_REDIS: "redis://db-redis:6379"
      DATABASE_URL_MONGODB: "mongodb://mongo:mongo123@db-mongodb:27017/appdb?authSource=admin"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db-postgres
      - db-redis
      - db-mongodb
